### PR TITLE
Add Carthage supporting

### PR DESCRIPTION
**Pull request by srj0x0**

### CODE REVIEW

**Comment by LeoNatan** [comment]
Hello,

I see a lot of changes in this PR for a relatively simple task. I don't think they are necessary. All it takes is to make the framework's scheme shared, which I will do right now.

**Comment by LeoNatan** [comment]
I see you've done that too in a separate commit. Did you mean to only submit that to the PR?

**Comment by srj0x0** [comment]
You right, it's not required. Could also add Cocoapods supporting?

**Comment by LeoNatan** [comment]
CocoaPods is not something I will add. I have a distinct dislike for it and I don't think it's a good idea to use in 2018. Since it is possible to use Carthage/submodules together with CocoaPods, I don't think it's necessary.

**Comment by srj0x0** [comment]
> I see you've done that too in a separate commit. Did you mean to only submit that to the PR?
@LeoNatan I'm not sure that it works without changing the project structure (I really don't remember why I changed something else 😱).

**Comment by LeoNatan** [comment]
That's the same structure I use in my other projects, which already support Carthage, so it should work.

**Comment by srj0x0** [comment]
@LeoNatan Thanks you!

**Comment by LeoNatan** [comment]
Thank you!

**Pull request closed without merging**
